Improve build and test for local use

diff --git a/tests/gitlab/build_and_test b/tests/gitlab/build_and_test
--- a/tests/gitlab/build_and_test
+++ b/tests/gitlab/build_and_test
@@ -24,6 +24,7 @@ spec=${SPEC:-""}
 
 sys_type=${SYS_TYPE:-""}
 py_env_path=${PYTHON_ENVIRONMENT_PATH:-""}
+ci_context=${CI:-""}
 
 threads=${THREADS:-""}
 
@@ -48,7 +49,9 @@ then
 
     prefix_opt=""
 
-    if [[ -d "/dev/shm" ]]
+    # Do not run on /dev/shm if only installing dependencies: they will be lost
+    # otherwise.
+    if [[ -d "/dev/shm" && "${option}" != "--deps-only" ]]
     then
         prefix="/dev/shm/${hostname}/${CI_PIPELINE_ID:-"NONE"}_${RANDOM}"
         mkdir -p ${prefix}
@@ -62,32 +65,42 @@ then
     echo "Installing dependencies."
     python tests/uberenv/uberenv.py --spec="${spec}" "${upstream_opt}" "${prefix_opt}"
 
+    # If only building the dependencies, store the host config file in a
+    # a dedicated directory not to pollute the top directory with it.
+    if [[ "${option}" == "--deps-only" && ! ${ci_context} ]]
+    then
+        mkdir -p host-configs
+        mv ${project_dir}/hc-*.mk host-configs/
+    fi
 fi
 
 # Host config file
-if [[ -z ${hostconfig} ]]
+if [[ "${option}" != "--deps-only" ]]
 then
-    # If no host config file was provided, we assume it was generated.
-    # This means we are looking of a unique one in project dir.
-    hostconfigs=( $( ls "${project_dir}/"hc-*.mk ) )
-    if [[ ${#hostconfigs[@]} == 1 ]]
-    then
-        hostconfig_path=${hostconfigs[0]}
-        echo "Found host config file: ${hostconfig_path}"
-    elif [[ ${#hostconfigs[@]} == 0 ]]
-    then
-        echo "No result for: ${project_dir}/hc-*.mk"
-        echo "Spack generated host-config not found."
-        exit 1
-    else
-        echo "More than one result for: ${project_dir}/hc-*.mk"
-        echo "${hostconfigs[@]}"
-        echo "Please specify one with HOST_CONFIG variable"
-        exit 1
-    fi
-else
-    # Using provided host-config file.
-    hostconfig_path="${project_dir}/host-configs/${hostconfig}"
+  if [[ -z ${hostconfig} ]]
+  then
+      # If no host config file was provided, we assume it was generated.
+      # This means we are looking of a unique one in project dir.
+      hostconfigs=( $( ls "${project_dir}/"hc-*.mk || true ) )
+      if [[ ${#hostconfigs[@]} == 1 ]]
+      then
+          hostconfig_path=${hostconfigs[0]}
+          echo "Found host config file: ${hostconfig_path}"
+      elif [[ ${#hostconfigs[@]} == 0 ]]
+      then
+          echo "No result for: ${project_dir}/hc-*.mk"
+          echo "Spack generated host-config not found."
+          exit 1
+      else
+          echo "More than one result for: ${project_dir}/hc-*.mk"
+          echo "${hostconfigs[@]}"
+          echo "Please specify one with HOST_CONFIG variable"
+          exit 1
+      fi
+  else
+      # Using provided host-config file.
+      hostconfig_path="${project_dir}/host-configs/${hostconfig}"
+  fi
 fi
 
 # Build Directory
