Revamping build-and-test: use bash options, add --data option, simplify config file management

diff --git a/tests/gitlab/build_and_test b/tests/gitlab/build_and_test
--- a/tests/gitlab/build_and_test
+++ b/tests/gitlab/build_and_test
@@ -14,13 +14,59 @@
 set -o errexit
 set -o nounset
 
-option=${1:-""}
+script_name=$(basename $0)
+
+function usage()
+{
+  echo "MFEM CI build and test driver"
+  echo ""
+  echo "Syntax:"
+  echo "> ${script_name} --spec \"spack spec\" [--deps-only] [--data]"
+  echo "                 [--build-root /path/to/build/resource]"
+  echo ""
+  echo "> ${script_name} --build-only [--data]"
+  echo "                 [--build-root /path/to/build/resource]"
+  echo ""
+  echo "> ${script_name} --test-only [--data]"
+  echo "                 [--build-root /path/to/build/resource]"
+  echo ""
+  echo "Options:"
+  echo " --spec"
+  echo "    The most common usage is to pass a spack spec to the script."
+  echo "    This spec may or may not specify \"mfem\" as the package, since it"
+  echo "    is the default."
+  echo ""
+  echo " --deps-only"
+  echo "    Only install MFEM dependencies. Will clone mfem-uberenv to drive a"
+  echo "    local instance on spack with which we install the dependencies."
+  echo "    This local spack instance is tuned to be completely independent"
+  echo "    from the user environment."
+  echo ""
+  echo " --build-only"
+  echo "    Only build MFEM, based on the existing configuration."
+  echo ""
+  echo " --test-only"
+  echo "    Only test MFEM, based on the existing configuration."
+  echo ""
+  echo " --data"
+  echo "    Make running tests with \"--data\" a requirement: will fail in the"
+  echo "    data directory is not present in mfem root directory."
+  echo "    Note: default behavior is to run data tests if data dir is present."
+  echo ""
+  echo " --build-root=/path/to/build/resource"
+  echo "    The script will use this directory to find the external resource"
+  echo "    needed, e.g. the data directory. Defaults to the parent location"
+  echo "    of the MFEM clone."
+  echo ""
+}
+
 hostname="$(hostname)"
 project_dir="$(pwd)"
 
-build_root=${BUILD_ROOT:-""}
-hostconfig=${HOST_CONFIG:-""}
-spec=${SPEC:-""}
+mode=""
+build_root=""
+spec=""
+with_data=$false
 
 sys_type=${SYS_TYPE:-""}
 py_env_path=${PYTHON_ENVIRONMENT_PATH:-""}
@@ -28,8 +74,44 @@ ci_context=${CI:-""}
 
 threads=${THREADS:-""}
 
+# Options
+while [[ $# -gt 0 ]]
+do
+    key="$1"
+
+    case $key in
+        --spec)
+            spec="$2"
+            shift # past argument
+            shift # past value
+            ;;
+        --deps-only|--build-only|--test-only)
+            mode="$key"
+            shift # past argument
+            ;;
+        --data)
+            with_data=$true
+            shift # past argument
+            shift # past value
+            ;;
+        --build-root)
+            build_root="$2"
+            shift # past argument
+            shift # past value
+            ;;
+        -h|--help)
+            usage
+            exit 0;
+            ;;
+        *)  # unknown option
+            echo "ERROR: option $key is unknown"
+            exit 1;
+            ;;
+    esac
+done
+
 # Dependencies
-if [[ "${option}" != "--build-only" && "${option}" != "--test-only" ]]
+if [[ "${mode}" != "--build-only" && "${mode}" != "--test-only" ]]
 then
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
     echo "~~~~~ Building Dependencies"
@@ -51,7 +133,7 @@ then
 
     # Do not run on /dev/shm if only installing dependencies: they will be lost
     # otherwise.
-    if [[ -d "/dev/shm" && "${option}" != "--deps-only" ]]
+    if [[ -d "/dev/shm" && "${mode}" != "--deps-only" ]]
     then
         prefix="/dev/shm/${hostname}/${CI_PIPELINE_ID:-"NONE"}_${RANDOM}"
         mkdir -p ${prefix}
@@ -62,68 +144,69 @@ then
     echo "Fetching uberenv."
     tests/gitlab/get_mfem_uberenv || ( echo "Error fetching Uberenv" && exit 1 );
 
+    echo "Removing existing configuration"
+    make distclean
+
     echo "Installing dependencies."
     python tests/uberenv/uberenv.py --spec="${spec}" "${upstream_opt}" "${prefix_opt}"
 
-    mkdir -p host-configs
-    mv ${project_dir}/hc-*.mk host-configs/
+    # Make sure that a configuration was generated by spack (part 1).
+    mv config/config.mk config/spack-config.mk
+    mv config/_config.hpp config/spack_config.hpp
 fi
 
+# Configuration
+if [[ "${mode}" != "--deps-only" ]]
+then
 # Host config file
-if [[ "${option}" != "--deps-only" ]]
-then
-  if [[ -z ${hostconfig} ]]
-  then
-      # If no host config file was provided, we assume it was generated.
-      # This means we are looking of a unique one.
-      hostconfigs=( $( ls "${project_dir}/host-configs/"hc-*.mk || true ) )
-      if [[ ${#hostconfigs[@]} == 1 ]]
-      then
-          hostconfig_path=${hostconfigs[0]}
-          echo "Found host config file: ${hostconfig_path}"
-      elif [[ ${#hostconfigs[@]} == 0 ]]
-      then
-          echo "No result for: ${project_dir}/host-configs/hc-*.mk"
-          echo "Spack generated host-config not found."
-          exit 1
-      else
-          echo "More than one result for: ${project_dir}/host-configs/hc-*.mk"
-          echo "${hostconfigs[@]}"
-          echo "Please specify one with HOST_CONFIG variable"
-          exit 1
-      fi
-  else
-      # Using provided host-config file.
-      hostconfig_path="${project_dir}/${hostconfig}"
-  fi
-fi
+# Make sure that a configuration was generated by spack (part 2).
+# Without this running the rest of the script would generate a new config.
+    if -f config/spack-config.mk && -f config/spack_config.mk
+    then
+        mv config/spack-config.mk config/config.mk
+        mv config/spack_config.hpp config/_config.hpp
+    else
+        echo "No result for at least one of"
+        echo "    ${project_dir}/config/spack-config.mk"
+        echo "    ${project_dir}/config/spack_config.hpp"
+        echo "ERROR: Spack generated configuration not found."
+        exit 1
+    fi
 
-# Build Directory
-if [[ -z ${build_root} ]]
-then
-    build_root=$(pwd)
+    # Build and Data Directories
+    if [[ -z ${build_root} ]]
+    then
+        # By default, build_root is the project parent dir.
+        build_root="${project_dir}/.."
+    else
+        # build_root is specified, so we need to link its content into the
+        # project parent dir.
+        ln -sf ${build_root}/data ${project_dir}/../
+    fi
+
+    if $with_data && ! -d ${build_root}/data
+    then
+        echo "ERROR: ${build_root}/data not found while asking for --data".
+    else
 fi
 
 # Build (also build when asked for testing, to make sure we test what we want)
-if [[ "${option}" != "--deps-only" ]]
+if [[ "${mode}" != "--deps-only" ]]
 then
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-    echo "~ Host-config: ${hostconfig_path}"
     echo "~ Project Dir: ${project_dir}"
+    echo "~ Build Root: ${build_root}"
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
     echo "~~~~~ Building MFEM"
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 
-    cp ${hostconfig_path} ${project_dir}/config/
-    ln -sf ${build_root}/data ${project_dir}/../
-
     make all -j ${threads}
 fi
 
 # Test
-if [[ "${option}" != "--deps-only" && "${option}" != "--build-only" ]]
+if [[ "${mode}" != "--deps-only" && "${mode}" != "--build-only" ]]
 then
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
     echo "~~~~~ Testing MFEM"
