In GitLab CI, distclean the MFEM directory after running the tests

diff --git a/tests/gitlab/build_and_test b/tests/gitlab/build_and_test
--- a/tests/gitlab/build_and_test
+++ b/tests/gitlab/build_and_test
@@ -232,13 +232,21 @@ then
     echo "~~~~~ Testing MFEM"
     echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 
-    return_code=0
-    make test 2>&1 | tee tests_output.txt || return_code=${?}
+    make test
+    test_status=$?
 
-    if grep -q "All tests passed." ./tests_output.txt
-    then
-        echo "SUCCESS: No error during tests" && exit 0
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+    echo "~~~~~ Cleaning MFEM"
+    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+
+    if make distclean > distclean.log 2>&1; then
+      echo "[make distclean]: OK"
     else
-        echo "ERROR: failure(s) while running MFEM tests" && exit 1
+      cat distclean.log
+      echo
+      echo "[make distclean]: FAILED (see above)"
     fi
+    rm -f distclean.log
+
+    exit $test_status
 fi
