Update branch-history script
Add new branch-history script to try to reduce the number of false
positives resulting from modification of large files (such as mesh.cpp,
fespace.cpp, etc.).

diff --git a/tests/scripts/branch-history b/tests/scripts/branch-history
--- a/tests/scripts/branch-history
+++ b/tests/scripts/branch-history
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env perl
 
 # Copyright (c) 2010, Lawrence Livermore National Security, LLC. Produced at the
 # Lawrence Livermore National Laboratory. LLNL-CODE-443211. All Rights reserved.
@@ -11,205 +11,82 @@
 # terms of the GNU Lesser General Public License (as published by the Free
 # Software Foundation) version 2.1 dated February 1999.
 
-# Print usage information
-case $1 in
-   -h|-help)
-      cat <<EOF
+my $branch_max_commits = 5;
+my $commit_max_files_changed = 5;
+my $max_blob_kb = 2;
+my $max_commit_kb = 3;
+my $max_branch_kb = 4;
 
-   $0 [-h|-help]
-   $0 {mfem_dir} [-commit <hash>] [-fast]
-   $0 {mfem_dir} [-range <hash>..<hash>] [-fast]
+my $status = 0; # Return code
 
-   where: {mfem_dir}  is the MFEM source directory [default value: ../..]
-          -h|-help    prints this usage information and exits
+my $current_branch = `git symbolic-ref --short HEAD`;
+my $commit_range = "master..$current_branch";
 
-   This script checks if the current branch history, defined as the commits that
-   will be merged in master (those shown in a GitHub PR), contains unusually
-   large files, unusually large number of changes in a commit, unusually large
-   number of commits, etc. (Optionally one can specify a different range of
-   commits to be checked via the -commit and -range options.)
+# Get SHA hash of all commits in this branch
+my @commits = split /\n/, `git log --pretty=format:%H $commit_range`;
 
-   The specific checks are provided at 3 levels: branch, commit and file.
+# Check if total number of commits in this branch exceeds the maximum allowable
+my $ncommits = scalar @commits;
+if ($ncommits > $branch_max_commits) {
+  printf STDERR
+    "\033[31mNumber of commits in this branch (%d) exceeds maximum allowable (%d).\033[0m\n",
+    $ncommits, $branch_max_commits;
+  $status = 1;
+}
 
-   Branch-level checks:
-   - Check if the branch contains unusually large number of commits
-   - Check if the branch adds/modifies unusually large files
+# Print SHA in blue
+sub print_sha {
+  printf STDERR "\033[34m    ^---> SHA: %s\033[0m\n", $_[0];
+}
 
-   Commit-level checks:
-   - Check if the commit changes an unusually large number of files
-   - Check if the commit changes an unusually large number of lines
+# Loop over each commit in this branch, and check for large diffs
+my $total_size = 0;
+foreach my $sha (@commits) {
+  my @blobs = `git diff-tree -r -M -C --no-commit-id $sha`;
+  my $nfiles_changed = scalar @blobs;
+  if ($nfiles_changed > $commit_max_files_changed) {
+    printf STDERR
+      "\033[31mNumber of files changed in one commit (%d) exceeds maximum allowable (%d).\033[0m\n",
+      $nfiles_changed, $commit_max_files_changed;
+    print_sha($sha);
+    $status = 1;
+  }
+  # Accumulate size of each commit in bytes
+  my $commit_size = 0;
+  foreach my $blob (@blobs) {
+    my @blob_split = (split /\s/, $blob);
+    my $src = @blob_split[2];
+    my $dst = @blob_split[3];
+    my $mode = @blob_split[4];
+    my $fname = @blob_split[5];
 
-   File-level checks:
-   - Check if the file is binary
-   - Check if the file is unusually large
-   - Check if an unusually large number of lines have been added to the file
-   - Check if an unusually large number of lines have been deleted from the file
+    my $blob_size = 0;
+    if ($mode eq "A") { $blob_size += int(`git cat-file -s $dst`); }
+    elsif ($mode =~ m/C\d*/) { $blob_size += int(`git cat-file -s $dst`); }
+    elsif ($mode eq "D") { }
+    elsif ($mode =~ m/M\d*/) { $blob_size += int(`git diff -U0 --binary $src $dst | gzip -c | wc -c`); }
+    elsif ($mode =~ m/R\d*/) { }
+    elsif ($mode eq "T") { }
+    elsif ($mode eq "U") { }
+    else { die "Unknown git status letter." }
+    if ($blob_size > $max_blob_kb*1024) {
+      $status = 1;
+      printf STDERR "\033[31mLarge change of size %d KB in file %s.\033[0m\n", ($blob_size/1024), $fname;
+      print_sha($sha);
+    }
+    $commit_size += $blob_size;
+  }
+  if ($commit_size > $max_commit_kb*1024) {
+    $status = 1;
+    printf STDERR "\033[31mLarge commit of size %d KB.\033[0m\n", $commit_size/1024;
+    print_sha($sha);
+  }
+  $total_size += $commit_size;
+}
 
-   The option -fast, allows to skip the checks that require checkout of the
-   individual commits, which could be convenient when there are local
-   changes. Currently, only the first two file-level checks will be skipped.
+if ($total_size > $max_branch_kb*1024) {
+  printf STDERR "\033[31mLarge total branch size: %d KB.\033[0m\n", $total_size/1024;
+  $status = 1;
+}
 
-   To be useful, the script should be run in a clean repository that doesn't
-   have any uncommitted changes and is not in a "detached HEAD" state.
-
-   Example usage: $0 ../..
-                  $0 ../../ -commit 8d50f48
-                  $0 ../../ -range eb2017b..5dd5511
-                  $0 ../../ -range master..d5f6f7e
-                  $0 ../../ -commit d5f6f7e -fast > /dev/null
-
-EOF
-      exit
-      ;;
-esac
-
-# Maximum number of acceptable commits in the branch
-branch_max_commits=100
-# Maximum number of acceptable files changed in any commit in the branch
-commit_max_files_changed=100
-# Maximum number of acceptable lines changed in any commit in the branch
-commit_max_lines_changed=3000
-# Maximum acceptable size (in K) of any file changed in any commit in the branch
-file_max_size=200
-# Maximum number of acceptable lines added to any file changed in any commit in the branch
-file_max_lines_added=1000
-# Maximum number of acceptable lines deleted from any file changed in any commit in the branch
-file_max_lines_deleted=1000
-
-# Setup
-cur_dir=`pwd`
-mfem_dir=$1
-if [ "$mfem_dir" = "" ]; then
-    mfem_dir="../.."
-fi
-cd $mfem_dir
-mfem_dir=`pwd`
-shift
-
-current_branch="$(git symbolic-ref --short HEAD)"
-commit_range="master..${current_branch}"
-if [ "$1" = "-commit" ]; then
-    shift
-    # check just the specified commit
-    commit="$1"
-    commit_range="`git rev-parse ${commit}^`..${commit}"
-    shift
-fi
-if [ "$1" = "-range" ]; then
-    shift
-    commit_range="$1"
-    shift
-fi
-
-checkout_commits=true
-if [ "$1" = "-fast" ]; then
-    checkout_commits=false
-fi
-
-# Check if the branch contains unusually large number of commits
-num_commits="$(git rev-list --count --no-merges ${commit_range})"
-if [ ${num_commits} -gt ${branch_max_commits} ]
-then
-    printf '\033[35m'"This branch contains unusually many commits: " 1>&2
-    printf "${num_commits} commits not in master"'\033[0m\n' 1>&2
-fi
-
-# Check if the branch adds/modifies unusually large files (this can catch large
-# binary files not addressed by the checks below)
-git_objects=$(git rev-list --objects --no-merges ${commit_range} \
-              | git cat-file --batch-check='%(objecttype) %(objectsize) %(rest)' \
-              | sed -n 's/^blob //p' \
-              | awk '{if (max[$2]<$1) max[$2]=$1} END {for (f in max) print max[f], f}' \
-              | sort --numeric-sort --key=1)
-
-while read -r obj; do
-    obj_fname="$(echo ${obj} | awk '{print $2}')"
-    obj_size="$(echo ${obj} | awk '{print int($1/1024)}')"
-    if [ ${obj_size} -gt ${file_max_size} ]
-    then
-        printf '\033[35m'"This branch adds/modifies a large file: " 1>&2
-        printf "${obj_fname} (size ${obj_size}K)"'\033[0m\n' 1>&2
-    fi
-done <<< "${git_objects}"
-
-# Check all the commits in the current branch (i.e. the commits that will be
-# merged in master, as shown in a GitHub PR):
-while read -r rev
-do
-    echo "Processing commit ${rev}..."
-    if [ "${checkout_commits}" = true ]
-    then
-        git checkout -q "${rev}"
-    fi
-    shortrev="$(git log -1 --format=%h ${rev})" # short commit hash
-
-    # Check if the commit changes an unusually large number of files
-    files_changed="$(git show --pretty="" --shortstat ${rev} | awk '{print $1}')"
-    if [ ${files_changed} -gt ${commit_max_files_changed} ]
-    then
-        printf '\033[36m'"Commit ${shortrev} changes unusually many files: " 1>&2
-        printf "${files_changed} files changed"'\033[0m\n' 1>&2
-    fi
-
-    # Check if the commit changes an unusually large number of lines
-    lines_changed="$(git show --pretty="" --shortstat ${rev} | awk '{print $4+$6}')"
-    if [ ${lines_changed} -gt ${commit_max_lines_changed} ]
-    then
-        printf '\033[36m'"Commit ${shortrev} makes unusually many changes: " 1>&2
-        printf "${lines_changed} total lines changed"'\033[0m\n' 1>&2
-    fi
-
-    # Check all the files modified in the current commit:
-    while read -r filelog
-    do
-        fname="$(echo ${filelog} | awk '{print $3}')"
-
-        if [ -e $fname ] && [ "${checkout_commits}" = true ] # exclude deleted files
-        then
-            # Check if the file is binary (non-text file as reported by "file")
-            binary="$(file -b ${fname} | grep -v 'text')"
-            if [ -n "${binary}" ]
-            then
-                printf '\033[31m'"Commit ${shortrev} contains a binary file: " 1>&2
-                printf "${fname} (${binary})"'\033[0m\n' 1>&2
-            fi
-
-            # Check if the file is unusually large
-            file_size="$(du -k ${fname} | cut -f1)"
-            if [ ${file_size} -gt ${file_max_size} ]
-            then
-                printf '\033[31m'"Commit ${shortrev} adds/modifies a large file: " 1>&2
-                printf "${fname} (size ${file_size}K)"'\033[0m\n' 1>&2
-            fi
-        fi
-
-        # Check if an unusually large number of lines have been added to the file
-        file_lines_added="$(echo ${filelog} | awk '{print $1}')"
-        if [ "${file_lines_added}" != "-" ] # exclude binary files
-        then
-            if [ ${file_lines_added} -gt ${file_max_lines_added} ]
-            then
-                printf '\033[31m'"Commit ${shortrev} adds unusually many lines to " 1>&2
-                printf "${fname} (${file_lines_added} lines added)"'\033[0m\n' 1>&2
-            fi
-        fi
-
-        # Check if an unusually large number of lines have been deleted from the file
-        file_lines_deleted="$(echo ${filelog} | awk '{print $2}')"
-        if [ "${file_lines_deleted}" != "-" ] # exclude binary files
-        then
-            if [ ${file_lines_deleted} -gt ${file_max_lines_deleted} ]
-            then
-                printf '\033[31m'"Commit ${shortrev} deletes unusually many lines from " 1>&2
-                printf "${fname} (${file_lines_deleted} lines deleted)"'\033[0m\n' 1>&2
-            fi
-        fi
-    done < <(git show --pretty="" --numstat --no-renames ${rev})
-done < <(git rev-list --reverse --no-merges ${commit_range})
-
-# Return to the original branch and directory
-if [ "${checkout_commits}" = true ]
-then
-    git checkout -q ${current_branch}
-fi
-cd $cur_dir
+exit $status;
