Updating scripts

diff --git a/tests/scripts/runtest b/tests/scripts/runtest
--- a/tests/scripts/runtest
+++ b/tests/scripts/runtest
@@ -98,17 +98,18 @@ do
    if [ -s "$this_test.err" ]; then
       runtest_check=1
       echo "=== BEGIN error log from $this_test.err"
-      printf '\033[0;32m'
-      (cat $this_test.err) 1>&2
+      printf '\033[0;31m'
+      (cat $this_test.err | echo -e) 1>&2
       printf '\033[0m'
       echo "=== END error log from $this_test.err"
       # rm -f $this_test.err $this_test.out
    else
-      printf '\033[0;32m'"No errors\n"'\033[0m'
-      printf '\033[0;32m'
-      printf "No errors\n"
-      printf "No errors\n"
-      printf '\033[0m'
+      echo -en "\033[31m"
+      echo "No errors"
+      echo "No errors"
+      echo "No errors"
+      echo "No errors"
+      echo -en "\033[0m"
    fi
 done
 
