Updating scripts

diff --git a/tests/scripts/runtest b/tests/scripts/runtest
--- a/tests/scripts/runtest
+++ b/tests/scripts/runtest
@@ -80,7 +80,7 @@ do
       this_dir=`dirname $test`
    fi
    test_cmd[0]="$this_test"
-   printf "\nRunning test '${test_cmd[*]}'...\n"
+   printf "\nRunning test '${test_cmd[*]}'... "
    { $this_dir/"$this_test" "$mfem_dir" "${test_cmd[@]:1}" 2>&1 1>&3 |
      tee "$this_test.err"; } > "$this_test.out" 3>&1
 
@@ -97,19 +97,13 @@ do
    # Print the *.err file if not empty
    if [ -s "$this_test.err" ]; then
       runtest_check=1
+      printf '\033[31m'"FAILED\n"'\033[0m'
       echo "=== BEGIN error log from $this_test.err"
-      printf '\033[0;31m'
-      (cat $this_test.err | echo -e) 1>&2
-      printf '\033[0m'
+      (cat $this_test.err) 1>&2
       echo "=== END error log from $this_test.err"
       # rm -f $this_test.err $this_test.out
    else
-      echo -en "\033[31m"
-      echo "No errors"
-      echo "No errors"
-      echo "No errors"
-      echo "No errors"
-      echo -en "\033[0m"
+      printf '\033[32m' "OK\n" '\033[0m'
    fi
 done
 
